a_lr: 0.0001
algo: SD3
batch_size: 500
buffer_size: 100000
c_lr: 0.0001
episode_length: 500
epsilon: 0.5
epsilon_speed: 0.99998
game_name: snakes_3v3
gamma: 0.95
load_model: false
load_model_run: 0
load_model_run_episode: 4000
log_dir: '20211228_131045'
max_episodes: 50000
model_episode: 0
output_activation: softmax
save_interval: 1000
seed: 5
tau: 0.0001
